AppAdmin/Areas/Client/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppAdmin.Areas.Client.Models.ServiceClient;
using AppAdmin.Common;
using ModelViews.DTOs;
using ApiService = AppAdmin.Models.Service.ApiService;

namespace AppAdmin.Areas.Client.Controllers
{
    public class HomeController : Controller
    {
        // GET: Client/Home
        public ActionResult Index()
        {
            ViewBag.RandomTheoChuDe = ApiService.GetAllCate().Where(s => s.ID_root != null).Distinct().OrderBy(s => Guid.NewGuid()).Take(5).ToList();
            ViewBag.GetPartner = ApiService.GetAllPartner();
            var data = ApiService.GetAllMusic();
            ViewBag.GetSinger = data;
            ViewBag.GetTop10SongNew = data.Where(s => s.SongOrMV == true).OrderByDescending(s => s.MusicDayCreate).Take(10).ToList();
            ViewBag.GetTop10MVNew = data.Where(s => s.SongOrMV == false).OrderByDescending(s => s.MusicDayCreate).Take(10).ToList();
            return View();
        }


        public ActionResult RankMusicThisWeek(int id)
        {
            var data = ApiService.GetListRankThisWeek().Where(x => x.CateID == id).ToList();
            ViewBag.idCate = id;
            ViewBag.ListRank = data;
            return View();
        }

        public ActionResult NavigationMenu()
        {
            Session["UserSession"] = (UserDTO)Session[CommonConstants.USER_SESSION];
            if (Session["UserSession"]!=null)
            {
                var idUser = (UserDTO)Session[CommonConstants.USER_SESSION];
                Session["UserId"] = idUser.ID;
                ViewBag.getUserById = ApiService.GetUserById(idUser.ID);
            }
            else
            {
                Session["UserId"] = null;
                ViewBag.getUserById = null;
            }
            var data = ApiService.GetAllCateCon();
            ViewBag.getCate = data;
            ViewBag.getSubCate = data.Where(s => s.ID_root != null).ToList();
            ViewBag.getTheoChuDe = ApiService.GetAllCate().Where(s => s.ID_root != null).ToList();
            return PartialView();
        }

        public ActionResult SearchPage(string name)
        {
            var music = ApiService.GetAllMusic()
                .Where(x => x.MusicName.ToLower().ToString().Contains(name.ToLower()) ||
                            x.MusicNameUnsigned.ToLower().Contains(name.ToLower()))
               .ToList();
            ViewBag.Key = name;
            ViewBag.Music = music.Where(x => x.SongOrMV).Take(100).ToList();
            ViewBag.Video = music.Where(x => !x.SongOrMV).Take(100).ToList();
            ViewBag.Singer = ApiService.GetAllSinger().Where(x => x.UserName.ToLower().ToString().Contains(name.ToLower()) || x.UserNameUnsigned.ToLower().Contains(name.ToLower())).Take(100).ToList();
            ViewBag.PlayList = ApiService.GetAllPlaylist().Where(x => x.PlaylistName.ToLower().Contains(name.ToLower())).Take(100).ToList();
            //ViewBag.getAllPlaylistMusic = ApiService.GetAllPlaylistMusic();
            return View();
        }


        #region Search for search input

        [HttpGet]
        public JsonResult SearchMusicByKey(string name)
        {
            var list = ApiService.GetMusicByName(name)
                .Where(x => x.MusicName.ToLower().ToString().Contains(name.ToLower()) || x.MusicNameUnsigned.ToLower().Contains(name.ToLower()))
                .Take(5)
                .Where(x => x.SongOrMV == true)
                .ToList();

            return Json(new
            {
                data = list
            }, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public JsonResult SearchVideoByKey(string name)
        {
            var list = ApiService.GetMusicByName(name)
                .Where(x => x.MusicName.ToLower().ToString().Contains(name.ToLower()) || x.MusicNameUnsigned.ToLower().Contains(name.ToLower()))
                .Take(5)
                .Where(x => x.SongOrMV == false)
                .ToList(); return Json(new
                {
                    data = list
                }, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public JsonResult SearchSingerByKey(string name)
        {
            var list = ApiService.GetSingerByName(name).Where(x => x.UserName.ToLower().ToString().Contains(name.ToLower()) || x.UserNameUnsigned.ToLower().Contains(name.ToLower())).Take(5).ToList();

            return Json(new
            {
                data = list
            }, JsonRequestBehavior.AllowGet);

        }

        #endregion
    }
}

AppAdmin/Areas/Client/Controllers/SingerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppAdmin.Areas.Client.Models.ServiceClient;
using AppAdmin.Common;
using AppAdmin.Models.Service;
using ModelViews.DTOs;

namespace AppAdmin.Areas.Client.Controllers
{
    public class SingerController : Controller
    {
        // GET: Client/Singer
     
        public  ActionResult Index(int id)
        {
            ViewBag.SingerData = ApiService.GetAllSinger().SingleOrDefault(x => x.ID == id);
            ViewBag.ListMusic = ApiService.GetAllMusic().Where(x => x.SingerMusicDtOs.Any(k => k.SingerID == id)).ToList();
            ViewBag.PlayListMusic = ApiService.GetAllPlaylistMusic()
                .Where(x => x.MusicDto.SingerMusicDtOs.Any(k => k.SingerID == id)).ToList();
            var UserId = (UserDTO)Session[CommonConstants.USER_SESSION];
            Session["UserSession"] = (UserDTO)Session[CommonConstants.USER_SESSION];
            if (Session["UserSession"] != null)
            {
                if (ApiService.GetPlaylistByIdUser(UserId.ID).Count() > 0)
                {
                    ViewBag.getPlaylistByIdUser = ApiService.GetPlaylistByIdUser(UserId.ID);
                }
                else
                {
                    ViewBag.getPlaylistByIdUser = null;
                }
                
            }
            else
            {
                ViewBag.getPlaylistByIdUser = null;
            }
            return View();
        }
        public JsonResult AddMusicPlaylist(PlaylistMusicDTO playlistMusicDTO)
        {
            var data = ApiService.CreatePlaylistMusic(playlistMusicDTO);
            if (data != null)
            {
                return Json(new
                {
                    status = true
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new
            {
                status = false
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

AppAdmin/Controllers/HomeController.cs
using AppAdmin.Models.Service;
using ModelViews.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppAdmin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        #region Category
        public ActionResult ViewCreateCate()
        {
            ViewBag.IdRoot = ApiService.GetAllCate().Where(s => s.ID_root == null).ToList();
            ViewBag.GetAllCate = ApiService.GetAllCate().Where(s=>s.ID_root==null).ToList();
            return View();
        }
        public ActionResult ViewCateIdRoot(int id)
        {
            Session["idRoot"] = id;
            ViewBag.GetCateByIdRoot = ApiService.GetCateByIdRoot(id);
            ViewBag.IdRoot = ApiService.GetAllCate().Where(s => s.ID_root == null).ToList();
            return View();
        }
        public ActionResult EditCate(int id)
        {
            ViewBag.IdRoot = ApiService.GetAllCate();
            var data = ApiService.GetCateById(id);
            return View(data);
        }
        public ActionResult EditCateIdRoot(int id)
        {
            ViewBag.IdRoot = ApiService.GetAllCate();
            var data = ApiService.GetCateById(id);
            return View(data);
        }
        public ActionResult CreateCate(CategoryDTO categoryDTO)
        {
            var data = ApiService.CreateCate(categoryDTO);
            if (data != null)
            {
                return RedirectToAction("ViewCreateCate");
            }
            Session["Create"] = "Create Fail";
            return RedirectToAction("ViewCreateCate");
        }
        public ActionResult UpdateCate(CategoryDTO categoryDTO)
        {
            var data = ApiService.UpdateCate(categoryDTO);
            if (data != null)
            {
                return RedirectToAction("ViewCreateCate");
            }
            Session["Update"] = "Update Fail";
            return RedirectToAction("ViewCreateCate");
        }
        public ActionResult UpdateCateIdRoot(CategoryDTO categoryDTO)
        {
            var data = ApiService.UpdateCate(categoryDTO);
            if (data != null)
            {
                return RedirectToAction("ViewCateIdRoot", new { id = categoryDTO.ID_root });
            }
            Session["Update"] = "Update Fail";
            return RedirectToAction("ViewCreateCate");
        }
        public ActionResult DeleteCate(int id)
        {
            ApiService.DeleteCate(id);
            return RedirectToAction("ViewCreateCate");
        }
        public ActionResult DeleteCateIdRoot(int id)
        {
            ApiService.DeleteCate(id);
            return RedirectToAction("ViewCateIdRoot", new { id = Session["idRoot"] });
        }
        public ActionResult GetMusicByIdCate(int id)
        {
            var data = ApiService.GetAllMusic().Where(s => s.CategoryId == id).ToList();
            return View(data);
        }
        #endregion
        public ActionResult ViewLogout()
        {
            return PartialView();
        }
        public ActionResult LogOutAdmin()
        {
            Session[Common.CommonConstants.USER_SESSION] = null;
            return Redirect("https://localhost:44315/Client/Login/Login");
        }
    }
}

AppAdmin/Areas/Client/Views/Home/Index.cshtml
@using ModelViews.DTOs
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Client/Views/Shared/_LayoutClient.cshtml";
    List<MusicDTO> listSong = ViewBag.GetTop10SongNew;
    List<MusicDTO> listMV = ViewBag.GetTop10MVNew;
    List<MusicDTO> SingerMusic = ViewBag.GetSinger;
    List<PartnerDTO> listPartner = ViewBag.GetPartner;
    List<CategoryDTO> randomCate = ViewBag.RandomTheoChuDe;

}
@section js{

    <script>
        $(document).ready(function () {
            var msg1 = '@TempData["success"]'
            if (msg1 != '') {
                alertify.success(msg1); //display notify
            }
            var msg2 = '@TempData["error"]'
            if (msg2 != '') {
                alertify.error(msg2); //display notify
            }
            window.onload = function () {
                var itv = window.setInterval(function () { prevImages() }, 3000);
                var next = document.getElementById("btnNext");
                var prev = document.getElementById("btnPrev");
                if (next != null && prev != null) {
                    next.addEventListener("click", function () {
                        nextImages();
                    });
                    prev.addEventListener("click", function () {
                        prevImages();
                    });
                }
            };
            function nextImage(item) {
                item.style.left = parseInt(item.style.left) + item.offsetWidth + 10 + "px";
            }
            function nextImages() {
                var lsImg = document.getElementsByClassName("imgItem");
                for (var i = 0; i < lsImg.length; i++) {
                    nextImage(lsImg[i]);
                }
                createImgFirst();
            }
            function prevImage(item) {
                item.style.left = parseInt(item.style.left) - item.offsetWidth - 10 + "px";
            }
            function prevImages() {
                var lsImg = document.getElementsByClassName("imgItem");
                for (var i = 0; i < lsImg.length; i++) {
                    prevImage(lsImg[i]);
                }
                createImgLast();
            }
            function createImgFirst() {
                var containImg = document.getElementById("owl-wrapper");
                var lastA = $(".imgItem:last-child");
                var lastImg = $(".imgItem:last-child>img");
                var newA = document.createElement("a");
                newA.className = "imgItem";
                newA.target = "_blank";
                newA.href = lastA.attr("href");
                var newImg = document.createElement("img");
                newImg.src = lastImg.attr("src");
                newA.append(newImg);
                newA.style.left = parseInt(containImg.firstElementChild.style.left) - containImg.firstElementChild.offsetWidth - 10 + "px";
                lastA.remove();
                containImg.insertBefore(newA, containImg.firstElementChild);
            }
            function createImgLast() {
                var containImg = document.getElementById("owl-wrapper");
                if (containImg != null) {
                    var firstA = $(".imgItem:first-child");
                    var firstImg = $(".imgItem:first-child>img");
                    var newA = document.createElement("a");
                    newA.className = "imgItem";
                    newA.target = "_blank";
                    newA.href = firstA.attr("href");
                    var newImg = document.createElement("img");
                    newImg.src = firstImg.attr("src");
                    newA.append(newImg);
                    newA.style.left = parseInt(containImg.lastElementChild.style.left) + containImg.lastElementChild.offsetWidth + 10 + "px";
                    firstA.remove();
                    containImg.appendChild(newA);
                }
            }
        });
    </script>
}
<div class="gridMusic">
    <div class="gridLeft">
        <!--New Song-->
        <div>
            <label for="" class="lblMusic">Mới phát hành</label>
            <div class="listMusic">
                @foreach (var item in listSong)
                {
                    <div class="itemMusic">
                        <span class="viewMusic">
                            <i class="fas fa-headphones"></i> @item.MusicView
                        </span>
                        <a href="@Url.Action("Index","playMusic", new { id = item.ID})" style="font-size: 18px;"><img src="@item.LinkImage" alt="" class="imgMusic">@item.MusicName</a>
                        <div class="nameSinger">
                            <a href="PersonalSinger.html"></a>
                            @foreach (var itemSinger in SingerMusic)
                            {
                                if (itemSinger.ID == item.ID)
                                {
                                    foreach (var singers in itemSinger.SingerMusicDtOs)
                                    {

                                        if (itemSinger.SingerMusicDtOs.IndexOf(singers) + 1 == itemSinger.SingerMusicDtOs.Count)
                                        {
                                            <a href="@Url.Action("Index","Singer", new { id = singers.UserDto.ID })">@singers.UserDto.UserName.</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Index","Singer", new { id = singers.UserDto.ID })">@singers.UserDto.UserName,</a>
                                        }
                                    }
                                }

                            }
                        </div>
                    </div>
                }
            </div>
        </div>
        <!--New Song-->
        <!--New MV-->
        <div style="margin-top: 10px;">
            <label for="" class="lblMusic">MV mới</label>
            <div class="listMusic">
                @foreach (var item in listMV)
                {
                    <div class="itemMusic">
                        <span class="viewMusic">
                            <i class="fas fa-headphones"></i> @item.MusicView
                        </span>
                        <a href="@Url.Action("Index","playMusic", new { id = item.ID})" style="font-size: 18px;"><img src="@item.LinkImage" alt="" class="imgMusic">@item.MusicName</a>
                        <div class="nameSinger">
                            <a href=""></a>
                            @foreach (var itemSinger in SingerMusic)
                            {
                                if (itemSinger.ID == item.ID)
                                {
                                    foreach (var singers in itemSinger.SingerMusicDtOs)
                                    {
                                        if (itemSinger.SingerMusicDtOs.IndexOf(singers) + 1 == itemSinger.SingerMusicDtOs.Count)
                                        {
                                            <a href="@Url.Action("Index","Singer", new { id = singers.UserDto.ID })">@singers.UserDto.UserName.</a>
                                        }
                                        else
                                        {
                                            <a href="@Url.Action("Index","Singer", new { id = singers.UserDto.ID })">@singers.UserDto.UserName,</a>
                                        }
                                    }
                                }

                            }
                        </div>


                    </div>
                }
            </div>
        </div>
        <!--New MV-->
    </div>
    <div class="gridRight">
        <label for="" class="lblMusic">Chủ đề HOT</label>
        <div id="cateList">
            <ul>
                @foreach (var item in randomCate)
                {
                    <li><a href="@Url.Action("Index","listPlaylistByCate", new { id = item.ID})">@item.CateName</a></li>
                }
            </ul>
        </div>
    </div>
</div>
<!--Partner-->
<div id="partner">
    <label for="" style="font-size: 18px;text-transform: uppercase;">Liên kết và hợp tác</label>
    <div id="slideImg">
        <div id="owl-wrapper">
            @foreach (var item in listPartner)
            {
                @*<a href="@item.PartnerLink" class="imgItem" target="_blank"> <img src="@item.LinkImage"></a>*@
                <img src="@item.LinkImage">
            }
        </div>
        <div id="controlImg">
            <div id="btnPrev">
                <i class="fas fa-caret-left"></i>
            </div>
            <div id="btnNext">
                <i class="fas fa-caret-right"></i>
            </div>
        </div>
    </div>
</div>
<!--Partner-->

AppAdmin/Areas/Client/Views/Home/RankMusicThisWeek.cshtml
@using ModelViews.DTOs

@{
    ViewBag.Title = "RankMusicThisWeek";
    Layout = "~/Areas/Client/Views/Shared/_LayoutClient.cshtml";
    List<RankDTO> listRank = ViewBag.ListRank;
    var id = ViewBag.idCate;
    var data = listRank.FirstOrDefault(x => x.CateID == id);
    var musics = listRank.FirstOrDefault(x => x.SongOrMusic && x.CateID == id);
    var mvs = listRank.FirstOrDefault(x => !x.SongOrMusic && x.CateID == id);


    
}



@section js
{
    <script>
        $(document).ready(function () {
            var itemLenght = $('.itemBxh').length;
            for (let i = 1; i < itemLenght + 1; i++) {
                var item = $('.itemBxh:nth-child(' + i + ')');
                var itemNumber = $('.itemBxh:nth-child(' + i + ')>span:first-child');
                if (item.attr('data-grade') === "1") {
                    itemNumber.css('color', '#e74c3c');
                } else if (item.attr('data-grade') === "2") {
                    itemNumber.css('color', '#1abc9c');
                } else if (item.attr('data-grade') === "3") {
                    itemNumber.css('color', '#f39c12');
                }
            }
            $('#topicBxh>div>div').click(function () {
                $('#topicBxh>div>div').removeClass("activeTopicBxh");
                $(this).addClass("activeTopicBxh");
                if ($(this).attr("data-music") == "1") {
                    $('#songBxh').css("display", "block");
                    $('#mvBxh').css("display", "none");
                } else {
                    $('#songBxh').css("display", "none");
                    $('#mvBxh').css("display", "block");
                }
            });
        });
    </script>
}
<div id="content" class="container">
    @if (data != null)
    {
        <div id="topicBxh">
            <span>Bảng xếp hạng âm nhạc  @data.CategoryDto.CateName</span>
            <div>
                <div class="activeTopicBxh" data-music="1">Bài hát</div>
                <div data-music="0">Video</div>
            </div>
        </div>
        <p style="margin-left: 40px;">
            Bảng xếp hạng được thống kê và thay đổi và lúc 23h30 chủ nhật hàng tuần.
        </p>

        <div id="listBxh">
            <div>
                <span>@data.RMusicName (@data.RMusicStart.ToString("dd-MM-yyyy") - @data.RMusicEnd.ToString("dd-MM-yyyy") )</span>
                @*<span style="float: right;">
                    <a href="" style="color: white;font-weight: 700;">
                        <i class="far fa-play-circle"></i> Nghe toàn bộ
                    </a>
                </span>*@
            </div>
            <div id="songBxh" style="display: block;">
                @if (musics != null && musics.MusicDtos != null)
                {
                    foreach (var item in musics.MusicDtos)
                    {
                        <div class="itemBxh" data-grade="@item.GradeRank">
                            <span>@item.GradeRank</span>
                            <img src="@item.LinkImage" alt="">
                            <span>
                                <a href="@Url.Action("Index","playMusic",new {id = @item.ID})" style="font-size: 20px;">@item.MusicName</a><br>
                                <span><i class="fas fa-headphones"></i> @item.MusicView</span>
                                <span>
                                    @foreach (var singer in item.SingerMusicDtOs)
                                    {
                                        <a href="@Url.Action("Index","Singer", new { id = singer.UserDto.ID})">@singer.UserDto.UserName</a>
                                    }
                                </span>

                            </span>
                            <span style="left: 265px;top: -15px;">
                               
                                @*<span class="addPlaylist" style="cursor: pointer;">
                                    <i class="fas fa-plus-circle"></i> Thêm vào
                                    <ul>
                                        <li><a href="">Bài hát yêu thích</a> </li>
                                        <li><a href="">Test1</a></li>
                                        <li><a href="">Test2</a></li>
                                    </ul>
                                </span>*@
                            </span>
                        </div>
                    }
                }
                else
                {
                    <p>Chưa có dữ liệu</p>
                }
            </div>
            <div id="mvBxh" style="display: none;">
                @if (mvs != null && mvs.MusicDtos != null)
                {
                    foreach (var item in mvs.MusicDtos)
                    {
                <div class="itemBxh" data-grade="@item.GradeRank">
                    <span>@item.GradeRank</span>
                    <img src="@item.LinkImage" alt="">
                    <span>
                        <a href="@Url.Action("Index","playMusic",new {id = @item.ID})" style="font-size: 20px;">@item.MusicName</a><br>
                        <span><i class="fas fa-headphones"></i> @item.MusicView</span>
                        <span>
                            @foreach (var singer in item.SingerMusicDtOs)
                            {
                                <a href="@Url.Action("Index","Singer", new { id = singer.UserDto.ID})">@singer.UserDto.UserName</a>
                            }
                        </span>

                    </span>
                    <span style="left: 265px;top: -15px;">

                        @*<span class="addPlaylist" style="cursor: pointer;">
                <i class="fas fa-plus-circle"></i> Thêm vào
                <ul>
                    <li><a href="">Bài hát yêu thích</a> </li>
                    <li><a href="">Test1</a></li>
                    <li><a href="">Test2</a></li>
                </ul>
            </span>*@
                    </span>
                </div>
                    }
                }
            </div>
        </div>
    }
    else
    {
        <div id="topicBxh">
            <span>Bảng xếp hạng âm nhạc</span>

        </div>
        <p style="margin-left: 40px;">
            Bảng xếp hạng được thống kê và thay đổi và lúc 23h30 chủ nhật hàng tuần.
        </p>
        <div class="p-5">
            <h1 class="text-center">

                Chưa có dữ liệu

            </h1>
        </div>
    }
</div>