AppAdmin/Areas/Client/Controllers/EditPlaylistController.cs
using AppAdmin.Models.Service;
using ModelViews.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppAdmin.Areas.Client.Controllers
{
    public class EditPlaylistController : Controller
    {
        private string path = "";
        public EditPlaylistController()
        {
            path = "~/File/ImagePlaylist/";
        }
        // GET: Client/EditPlaylist
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EditPLaylist(int id)
        {
            Session["IdEditPl"] = id;
            ViewBag.getMusicByIdPlaylist = ApiService.GetMusicByIdPlaylist(id);
            ViewBag.getCate = ApiService.GetAllCate().Where(s => s.ID_root != null).ToList();
            var data = ApiService.GetPlaylistById(id);
            return View(data);
        }
        public ActionResult UpdatePlaylist(PlaylistDto playlistDTO)
        {
            try
            {
                //get Image have exist
                var currentFileName = ApiService.GetPlaylistById(playlistDTO.ID).PlaylistImage;
                //check name have deafault if exist ==> dont delete
                if (currentFileName == "default.png")
                {
                    if (playlistDTO.FileImage != null)
                    {
                        playlistDTO.PlaylistImage = DateTime.Now.Ticks + playlistDTO.PlaylistImage + ".png";
                        playlistDTO.FileImage.SaveAs(Server.MapPath(path + playlistDTO.PlaylistImage));
                        playlistDTO.FileImage = null;
                    }
                    else
                    {
                        playlistDTO.PlaylistImage = "default.png";
                    }
                }
                else
                {

                    if (playlistDTO.FileImage != null)
                    {
                        //delete file
                        var filePath = Server.MapPath(path + currentFileName);
                        if (System.IO.File.Exists(filePath))
                        {
                            System.IO.File.Delete(filePath);
                        }
                        playlistDTO.PlaylistImage = DateTime.Now.Ticks + playlistDTO.PlaylistImage + ".png";
                        playlistDTO.FileImage.SaveAs(Server.MapPath(path + playlistDTO.PlaylistImage));
                        playlistDTO.FileImage = null;
                    }
                    else
                    {
                        playlistDTO.PlaylistImage = currentFileName;
                    }
                }
                var data = ApiService.UpdatePlaylist(playlistDTO);
                if (data != null)
                {
                    SetAlert("Update success!", "success");
                    return RedirectToAction("PersonalUser", "PersonalUser", new { id = Session["UserId"] });
                }
                SetAlert("Update fail!", "danger");
                return RedirectToAction("EditPLaylist", new { id = playlistDTO.ID });
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                SetAlert("Update fail!", "danger");
                return RedirectToAction("EditPLaylist", new { id = playlistDTO.ID });
            }


        }
        public ActionResult DeleteMusicInPlaylist(int id)
        {
            ApiService.DeletePlaylistMusic(id);
            SetAlert("Delete success", "success");
            return RedirectToAction("EditPLaylist",new { id = Session["IdEditPl"] });
        }
        public ActionResult DeletePlaylistAndPlaylistMusic(int id)
        {
            ApiService.DeletePlaylistAndPlaylistMusic(id);
            SetAlert("Delete success", "success");
            return RedirectToAction("PersonalUser", "PersonalUser", new { id = Session["UserId"] });
        }
        protected void SetAlert(string message, string type)
        {
            TempData["AlertMessage"] = message;
            if (type == "success")
            {
                TempData["AlertType"] = "alert-success";
            }
            else if (type == "warning")
            {
                TempData["AlertType"] = "alert-warning";
            }
            else if (type == "error")
            {
                TempData["AlertType"] = "alert-danger";
            }
        }
    }
}

AppAdmin/Areas/Client/Views/EditPlaylist/EditPLaylist.cshtml
@using ModelViews.DTOs
@model ModelViews.DTOs.PlaylistDto
@{
    ViewBag.Title = "EditPLaylist";
    Layout = "~/Areas/Client/Views/Shared/_LayoutClient.cshtml";
    List<PlaylistMusicDTO> getMusicByIdPlaylist = ViewBag.getMusicByIdPlaylist;
    List<CategoryDTO> getCate = ViewBag.getCate;
}
@section js {
    <script>
        $(document).ready(function () {
            $('#inputImage').change(function (event) {
                var tmppath = URL.createObjectURL(event.target.files[0]);
                $('#upImage').fadeIn("fast").attr("src", tmppath);
            });
        });
    </script>
    <script>
        $(function () {
            $('#AlertBox').removeClass('hide');
            $('#AlertBox').delay(1000).slideUp(500);
        });
    </script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        $('.select2').select2();
    </script>
}
<!--Start Content-->
<div id="content" class="container">
    @if (TempData["AlertMessage"] != null)
    {
        <div id="AlertBox" class="alert @TempData["AlertType"]" hide>
            @TempData["AlertMessage"]
        </div>
    }
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="margin-left: 40px;margin-top: 40px;">

        <div class="image-cropper-wp">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h4>CHỈNH SỬA PLAYLIST</h4>
                    <form method="post" action="@Url.Action("UpdatePlaylist","EditPLaylist")" enctype="multipart/form-data">
                        <div class="form-group">
                            <input type="hidden" value="@Model.ID" name="ID" />
                            <input type="hidden" value="@Session["UserId"]" name="UserId" />
                            <label for="" style="margin-right: 12px;">Tên Playlist: </label>
                            <input type="text" name="PlaylistName" value="@Model.PlaylistName" id="" style="width: 40%;">
                        </div>
                        <div class="form-group">
                            <label for="">Chọn Thể loại: </label>
                            <select name="CateId" id="UserId" style="width:38%;" class="select2">

                                @foreach (var item in getCate)
                                {
                                    if (item.ID == Model.CateID)
                                    {
                                        <option selected="selected" value="@item.ID">@item.CateName</option>
                                    }
                                    else
                                    {
                                        <option value="@item.ID">@item.CateName</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="" style="margin-right: 50px;">Mô tả: </label>
                            <textarea name="PlaylistDescription" id="" maxlength="1000" style="width: 38%;">@Model.PlaylistDescription</textarea>
                        </div>
                        <div class="maincrop-img" style="margin-left: 95px;margin-bottom: 10px;">
                            <div class="image-crp-int">
                                <div class="img-preview img-preview-custom">
                                    <img src="@Model.LinkImage" id="upImage" style="width: 300px; height: 200px;;">
                                </div>
                            </div>
                            <div class="image-crp-img">
                                <div class="btn-group images-cropper-pro">
                                    <label title="Upload image file" for="inputImage"
                                           class="btn btn-primary img-cropper-cp waves-effect">
                                        <input type="file" accept="image/*" name="FileImage" id="inputImage" class="hide">
                                        Upload new image
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" style="margin-left: 92px;">
                            <input type="submit" class="btn btn-success" value="Cập nhật">
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h4>DANH SÁCH BÀI HÁT</h4>
                    <div class="bsc-tbl-st">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    @*<th>#</th>*@
                                    <th>Tên bài hát</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in getMusicByIdPlaylist)
                                {
                                    <tr>

                                        <td><a href="">@item.MusicDto.MusicName</a></td>
                                        <td><a href="@Url.Action("DeleteMusicInPlaylist","EditPlaylist",new { id = item.ID})"><i class="fas fa-trash-alt"></i></a></td>

                                        @*<td>1</td>*@
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--End content-->